name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
        
    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.ART_HOSTNAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.SERVICE_NAME }} -f Dockerfile .
        gcloud auth configure-docker ${{ secrets.ART_HOSTNAME }} --quiet
        docker push ${{ secrets.ART_HOSTNAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
        
    - name: Trivy base image scanning.
      run: |
        chmod u+x ./trivy-docker-image-scan.sh
        ./trivy-docker-image-scan.sh
        
    - name: Change target image name.
      if: success()
      run: |
        sed -i 's/replace/${{ secrets.ART_HOSTNAME }}\/${{ secrets.PROJECT_ID }}\/${{ secrets.REPO_NAME }}\/${{ secrets.SERVICE_NAME }}:${{ github.sha }}/' k8s_deployment_service.yaml
        
    - name: Deploy to Kubernetes
      run: |
        gcloud beta compute --project "$GCLOUD_PROJECT_ID" scp k8s_deployment_service.yaml bitbucket@"bastion-01":~/real-deployment.yaml --zone "asia-southeast1-a"
        gcloud compute ssh --zone "asia-southeast1-a" "bastion-01" --project "sn2-dev2" --command "kubectl apply -f real-deployment.yaml"
        gcloud compute ssh --zone "asia-southeast1-a" "bastion-01" --project "sn2-dev2" --command "rm -rf real-deployment.yaml"
        
