name: CI Pipeline
on:
  push:
    branches: [ "main", "release/*"]
    tags:
      - 'v*'  # Trigger the workflow on tags like v1.0, v2.0, etc...
  pull_request:
    branches: [ "feature/**", release/** ]
  workflow_dispatch:
  
jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/devopscicd.yml
    secrets:
         GCR_SERVICE_ACCOUNT_KEY: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY_DEV }}
         ART_HOSTNAME: ${{ secrets.ART_HOSTNAME }}
         REPO_NAME: ${{ secrets.REPO_NAME }}
         PROJECT_ID: ${{ secrets.PROJECT_ID_DEV }}
         DEPLOY_REGION: ${{ secrets.DEPLOY_REGION }}
         SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
